docs: mention required debugLevel (#15)
Example `nitro.json` is not complete. It misses `logLevel` property.

> Error: Invalid nitro.json config file! `logLevel` must be 'debug' | 'info' | 'warning' | 'error', but is undefined.

Added `logLevel` to docs.